### ISSUE TITLE
Any plans to make this compatible with Mathematica notebooks?

### ISSUE THREAD

**Issue by gtusr** [hammerfunctor/tm-mathematica#1]
Native support for loading and interacting with Mathematica notebooks from within TeXmacs would be great, but I'd be satisfied with a plugin that can faithfully import and export a Mathematica notebook for the time being.

**Comment by hammerfunctor** [comment]
Import content of a notebook as a package: https://mathematica.stackexchange.com/questions/111846/import-another-notebook-as-if-it-were-a-package

Convert a notebook into `mma` sessions of TeXmacs holding the structure: I don't see the use case here

Export all `mma` sessions into a wolfram script with filename extension `.wls`: see https://github.com/hammerfunctor/tm-mathematica/blob/wolframscript/bin/tmdumpcode1. You can also load the file https://github.com/hammerfunctor/tm-mathematica/blob/wolframscript/bin/session-extraction.scm in init file and bind `(save-lan-to-file "mma" "" "wls")` to some kbd shortcut. The exported `wls` file can be executed by `wolframscript -f file.wls`.

Converting from and to notebook format is hardly useful for my experience with mathematica. When Texmacs present, I don't real need notebooks to do presentations. These functionalities may be implemented in the future. But as of now, they are less attractive to me.

Patches are welcome though.

**Comment by gtusr** [comment]
Mathematica .nb notebooks are Wolfram language expressions just like everything else in Mathematica.  This means that they can be easily manipulated as Wolfram data from within the Wolfram language just like any other Wolfram expressions.  

This tight coupling of code syntax to document formatting is another expression of 'homoiconicity.'   Evaluating a notebook expression then renders its content in the GUI interface.  

Many enjoy using the Mathematica notebook interface but complain about its proprietary closed development cycle.

[Jupyter, Mathematica, and the Future of the Research Paper](https://paulromer.net/jupyter-mathematica-and-the-future-of-the-research-paper/)

It would therefore be nice as a long term goal to build an alternative implementation of the standard Mathematica front-end (also known as the "notebook interface") using TeXmacs and let it connect optionally to the Wolfram kernel (also known as the "Wolfram engine") or to mathics.  This would probably also require implementing the MathLink interface in order to faithfully reproduce communication between the Mathematica front-end and a kernel.

**Comment by hammerfunctor** [comment]
> This means that they can be easily manipulated as Wolfram data from within the Wolfram language just like any other Wolfram expressions.

See https://mathematica.stackexchange.com/questions/111846/import-another-notebook-as-if-it-were-a-package for how to manipulate you Wolfram notebook data.

> Evaluating a notebook expression then renders its content in the GUI interface.

That's how this package works.

> ... an alternative implementation of the standard Mathematica front-end ...

Have you ever used this package?

>  This would probably also require implementing the MathLink interface in order to faithfully reproduce communication between the Mathematica front-end and a kernel.

See https://github.com/hammerfunctor/tm-mathematica/blob/wolframscript/wolfram/tmWolfram.wls#L42

What's your point here?

**Comment by gtusr** [comment]
> See https://mathematica.stackexchange.com/questions/111846/import-another-notebook-as-if-it-were-a-package for how to manipulate you Wolfram notebook data.

Thanks for the link.

In the long run, I'm still looking for native support of Wolfram document expressions within TeXmacs -- not just offline converters between the two formats and not just the ability to load and evaluate a set of definitions and expressions from a .nb document.

The simplest reason is that this reduces the overall 'cognitive load' for the average user.  As it stands currently, the TeXmacs document is represented internally as a scheme expression, while the code inside that document, in the case that we're discussing here, would be written in the Wolfram language.  This makes it harder to manipulate the document as an expression natively from within the Wolfram language.  

As documents themselves start to become more dynamic entities, as part of the move away from static results published in LaTeX-typeset papers toward a world full of 'reproducible research', I think that a single framework, to wit, the Wolfram language, for generating both the results and the document used to present them, becomes a more interesting proposition.

Have a look at this:  [Mathematica Journal](https://www.mathematica-journal.com/)  

>> ... an alternative implementation of the standard Mathematica front-end ...
> 
> Have you ever used this package?

From the demo, it looks very much like a TeXmacs-equivalent of the Jupyter-based "notebook interface" that Wolfram recently released as open source.  Wolfram's Jupyter notebook interface has been criticized in one of the forums as providing little more than a 'dumb terminal' interface to the Wolfram engine, possibly in order to further promote its own (far more advanced) proprietary native notebook front-end given the criticism that Wolfram has recently received from prominent researchers like Paul Romer regarding the closed nature of its internal product development cycle (_vide supra_).

> > This would probably also require implementing the MathLink interface in order to faithfully reproduce communication between the Mathematica front-end and a kernel.
> 
> See https://github.com/hammerfunctor/tm-mathematica/blob/wolframscript/wolfram/tmWolfram.wls#L42
> 
> What's your point here?

I'll have to study that further.

**Comment by hammerfunctor** [comment]
Thanks for your clarification. This package aims to run self-contained and legitimate wolfram language expressions facilitating the note-taking experience in TeXmacs. So no matter how simple the extra components I add to this package is, it becomes dependency of expressions in your TeXmacs documents when you use them. And your codes are no longer self-contained when you export them. I'm not interested and don't want to maintain the extra complexity here.

Another way to import you nb document is to open it using Mathematica, and `Save As` a directly importable `.m` package.

> As documents themselves start to become more dynamic entities, as part of the move away from static results published in LaTeX-typeset papers toward a world full of 'reproducible research', I think that a single framework, to wit, the Wolfram language, for generating both the results and the document used to present them, becomes a more interesting proposition.

I don't care about those fancy nonsense.

> ... TeXmacs-equivalent of the Jupyter-based "notebook interface" ...

The goal here is to be a terminal. For wolfram language, I don't care about language server either, not to mention the extremely complicated notebook front-end[^1]

> For the front end, however, a significant amount of specialized code is needed to support each different type of user interface environment. The front end contains about 700,000 lines of system‐independent C++ source code, of which roughly 200,000 lines are concerned with expression formatting. Then there are between 50,000 and 100,000 lines of specific code customized for each user interface environment. 

[^1]: https://reference.wolfram.com/language/tutorial/TheInternalsOfTheWolframSystem.html

**Comment by gtusr** [comment]
> > As documents themselves start to become more dynamic entities, as part of the move away from static results published in LaTeX-typeset papers toward a world full of 'reproducible research', I think that a single framework, to wit, the Wolfram language, for generating both the results and the document used to present them, becomes a more interesting proposition.
> 
> I don't care about those fancy nonsense.

Fair enough.  I just don't see the value proposition in my line of work for using TeXmacs as a 'dumb terminal' interface to the Wolfram language rather than Jupyter.  The latter has already gained a lot more traction within the data science community than TeXmacs ever will, has extensive corporate backing, and has an official plugin released by Wolfram, even though the math typesetting capabilities of TeXmacs far exceed the latter.    

Still hoping that someday we'll be able to create rich Wolfram-compatible notebooks from within TeXmacs that we can then use Mathics to evaluate in order to provide a _fully_ open source and _fully_ compatible computer algebra system alternative to Mathematica.   The road to that vision is long for sure, but it now looks like your project will not lie on the path that takes us there. 

Thank you for your response.
