### ISSUE TITLE
Error while plotting

### ISSUE THREAD

**Issue by aburousan** [hammerfunctor/tm-mathematica#2]
I have installed this and really loved it. I can do all things which are non plotting type. But the problem starts while trying to plot. The result is like this:
![Screenshot from 2024-08-04 12-43-33](https://github.com/user-attachments/assets/3dea8d7c-0752-46a3-b2fe-5e155007e74a)
Any idea how i can fix this?, 
I am using Ubuntu 24.04

**Comment by hammerfunctor** [comment]
I met no problem doing exactly the same thing as you did. Which branch are you staying for now? Try `main` if you haven't.

**Comment by aburousan** [comment]
After a reinstalling it's fine now.
Although there was a error use to a library.
For future Ubuntu users, to remove the error of libML64i4.so library use 
```
MATH=`realpath $(which math) | sed -e 's=/Executables/math$=/SystemFiles/Links/MathLink/DeveloperKit/Linux-x86-64/CompilerAdditions='`
sudo ln -s $MATH/libML64i4.so /usr/lib/libML64i4.so

```
